### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by zakaria-chahboun** [frinyvonnick/node-html-to-image#120]
First of all i want to thanks all people behind this amazing open source project!
I used this module in my node.js project to generate a quick template for (bill), i succeeded to that (like image below).

But. i don't want to use a fixed height! because the bill depend on the 'elements' of my table!
So, What i can do for that?
> if i don't specify the height or give it "height: auto" the image gives me a default height! which is tall and not fit to my height.

![photo_2021-07-18_13-25-43](https://user-images.githubusercontent.com/18173275/126067304-2929428b-6f5a-40e6-9de8-fc19ca4fc0cb.jpg)

**Comment by zakaria-chahboun** [comment]
Fixed by add `height: fit-content` to my css:

```css
body {
max-width: 95mm;
height: fit-content;
border: 2px solid black;
border-radius: 4px;
padding: 10px;
}
```
:+1:
